services:
  - type: web
    name: developer-productivity-api
    env: python
    repo: https://github.com/Aradhya-AI/Developer-Productivity-MVP.git
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
